/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.xet.logscatter;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class LogScatterApplication {

    public static void main(String[] args) {
		SpringApplication.run(LogScatterApplication.class, args);
    }
}
